import { getData, http, postData, putData } from '@/utils/request'
import type {
  AuditLog,
  ApiResponse,
  Bom,
  ChangeImpact,
  ChangeOrder,
  ConfirmationToken,
  Customer,
  DashboardData,
  DashboardPeriodCode,
  DocumentVersion,
  ExportTask,
  ImportTask,
  InspectionSpec,
  Message,
  PageResult,
  ProcessRoute,
  Project,
  ProjectWorkspace,
  ProjectMember,
  QrCodeBinding,
  ReportOverview,
  Requirement,
  Risk,
  RiskAction,
  RuleParam,
  Sample,
  SampleCheck,
  SearchResultItem,
  Task,
  UserProfile,
  Workbench
} from '@/types'

export const api = {
  login: (data: { username: string; password: string }) => postData<any>('/admin/auth/login', data),
  refresh: (refreshToken: string) => postData<any>('/admin/auth/refresh', { refreshToken }),
  logout: (refreshToken?: string) => postData<void>('/admin/auth/logout', { refreshToken }),
  me: () => getData<any>('/admin/auth/me'),
  profile: () => getData<UserProfile>('/admin/profile'),
  updateProfile: (data: Pick<UserProfile, 'nickname' | 'phone' | 'email' | 'gender' | 'version'>) => putData<UserProfile>('/admin/profile', data),
  changePassword: (data: { currentPassword: string; newPassword: string }) => putData<void>('/admin/profile/password', data),
  uploadAvatar: async (file: File) => {
    const form = new FormData()
    form.append('file', file)
    const response = await http.post<ApiResponse<UserProfile>>('/admin/profile/avatar', form)
    return response.data.data
  },
  profileAvatar: async () => {
    const response = await http.get<Blob>('/admin/profile/avatar', { responseType: 'blob' })
    return URL.createObjectURL(response.data)
  },
  workbench: () => getData<Workbench>('/admin/workbench'),
  dashboard: (params?: { period?: DashboardPeriodCode; startDate?: string; endDate?: string }) =>
    getData<DashboardData>('/admin/dashboard', params),
  search: (keyword?: string) => getData<PageResult<SearchResultItem>>('/admin/search', { keyword }),
  customers: (keyword?: string) => getData<PageResult<Customer>>('/admin/customers', { keyword }),
  createCustomer: (data: Partial<Customer>) => postData<Customer>('/admin/customers', data),
  projects: (keyword?: string) => getData<PageResult<Project>>('/admin/projects', { keyword }),
  createProject: (data: Record<string, unknown>) => postData<Project>('/admin/projects', data),
  project: (id: number) => getData<any>(`/admin/projects/${id}`),
  projectWorkspace: (id: number) => getData<ProjectWorkspace>(`/admin/projects/${id}/workspace`),
  createProjectFlowQr: (id: number) => postData<QrCodeBinding>(`/admin/projects/${id}/flow-qr`),
  submitReview: (id: number) => postData<Project>(`/admin/projects/${id}/submit-review`),
  requirements: (projectId: number) => getData<PageResult<Requirement>>(`/admin/projects/${projectId}/requirements`),
  saveRequirement: (projectId: number, data: Record<string, unknown>) => postData<Requirement>(`/admin/projects/${projectId}/requirements`, data),
  confirmRequirement: (id: number, data: Record<string, unknown>) => postData<Requirement>(`/admin/requirements/${id}/confirm`, data),
  members: (projectId: number) => getData<PageResult<ProjectMember>>(`/admin/projects/${projectId}/members`),
  addMember: (projectId: number, data: Record<string, unknown>) => postData<ProjectMember>(`/admin/projects/${projectId}/members`, data),
  documents: (projectId?: number) => getData<PageResult<DocumentVersion>>('/admin/documents', { projectId }),
  createDocument: (projectId: number, data: Record<string, unknown>) =>
    postData<DocumentVersion>(`/admin/documents/${projectId}/versions`, data),
  uploadDocumentFile: async (projectId: number, file: File) => {
    const form = new FormData()
    form.append('projectId', String(projectId))
    form.append('file', file)
    const response = await http.post('/admin/files/upload', form)
    return response.data.data as { id: number; fileName: string; contentType: string; fileSize: number; sha256: string; downloadUrl: string }
  },
  publishDocument: (id: number) => postData<DocumentVersion>(`/admin/document-versions/${id}/publish`),
  createDocumentQr: (id: number) => postData<QrCodeBinding>(`/admin/document-versions/${id}/qr`),
  boms: (projectId?: number) => getData<PageResult<Bom>>('/admin/boms', { projectId }),
  createBom: (data: Record<string, unknown>) => postData<Bom>('/admin/boms', data),
  processRoutes: (projectId?: number) => getData<PageResult<ProcessRoute>>('/admin/process-routes', { projectId }),
  createProcessRoute: (data: Record<string, unknown>) => postData<ProcessRoute>('/admin/process-routes', data),
  inspectionSpecs: (projectId?: number) => getData<PageResult<InspectionSpec>>('/admin/inspection-specs', { projectId }),
  createInspectionSpec: (data: Record<string, unknown>) => postData<InspectionSpec>('/admin/inspection-specs', data),
  publishTechnicalPackage: (projectId: number) => postData<Record<string, unknown>>(`/admin/projects/${projectId}/technical-package/publish`),
  syncTechnicalPackageTasks: (projectId: number) => postData<{ updatedTaskCount: number; versionNo: string }>(`/admin/projects/${projectId}/technical-package/sync-tasks`),
  samples: (projectId?: number) => getData<PageResult<Sample>>('/admin/samples', { projectId }),
  createSample: (data: Record<string, unknown>) => postData<Sample>('/admin/samples', data),
  submitSampleConfirm: (id: number) => postData<Sample>(`/admin/samples/${id}/submit-confirm`),
  confirmSample: (id: number, data: Record<string, unknown>) => postData<Sample>(`/admin/samples/${id}/confirm`, data),
  sampleChecks: (id: number) => getData<PageResult<SampleCheck>>(`/admin/samples/${id}/checks`),
  addSampleCheck: (id: number, data: Record<string, unknown>) => postData<SampleCheck>(`/admin/samples/${id}/checks`, data),
  createConfirmToken: (id: number) => postData<ConfirmationToken>(`/admin/samples/${id}/confirm-token`),
  changes: (projectId?: number) => getData<PageResult<ChangeOrder>>('/admin/changes', { projectId }),
  createChange: (data: Record<string, unknown>) => postData<ChangeOrder>('/admin/changes', data),
  analyzeChange: (id: number) => postData<ChangeImpact[]>(`/admin/changes/${id}/analyze-impact`),
  impacts: (id: number) => getData<ChangeImpact[]>(`/admin/changes/${id}/impacts`),
  approveChange: (id: number, data?: Record<string, unknown>) => postData<ChangeOrder>(`/admin/changes/${id}/approve`, data),
  feedbackChange: (id: number, data: Record<string, unknown>) => postData<ChangeOrder>(`/admin/changes/${id}/feedback`, data),
  closeChange: (id: number) => postData<ChangeOrder>(`/admin/changes/${id}/close`),
  tasks: (projectId?: number) => getData<PageResult<Task>>('/admin/tasks', { projectId }),
  createExecutionTask: (data: Record<string, unknown>) => postData<Task>('/admin/execution/tasks', data),
  startTask: (id: number, data?: Record<string, unknown>) => postData<Task>(`/admin/tasks/${id}/start`, data),
  pauseTask: (id: number, data?: Record<string, unknown>) => postData<Task>(`/admin/tasks/${id}/pause`, data),
  completeTask: (id: number, data?: Record<string, unknown>) => postData<Task>(`/admin/tasks/${id}/complete`, data),
  feedbackTask: (id: number, data: Record<string, unknown>) => postData<Task>(`/admin/tasks/${id}/feedback`, data),
  reportException: (data: Record<string, unknown>) => postData<Risk>('/admin/execution/exceptions', data),
  deliveries: (projectId?: number) => getData<PageResult<Record<string, unknown>>>('/admin/deliveries', { projectId }),
  createDelivery: (data: Record<string, unknown>) => postData<Record<string, unknown>>('/admin/deliveries', data),
  risks: (projectId?: number) => getData<PageResult<Risk>>('/admin/risks', { projectId }),
  riskActions: (riskId: number) => getData<RiskAction[]>(`/admin/risks/${riskId}/actions`),
  createRiskAction: (riskId: number, data: Record<string, unknown>) => postData<RiskAction>(`/admin/risks/${riskId}/actions`, data),
  closeRiskAction: (actionId: number, data: { closeSummary: string; version: number }) => postData<RiskAction>(`/admin/risk-actions/${actionId}/close`, data),
  messages: (status?: string) => getData<PageResult<Message>>('/admin/messages', { status }),
  readMessage: (id: number) => postData<Message>(`/admin/messages/${id}/read`),
  overview: () => getData<ReportOverview>('/admin/reports/overview'),
  savedViews: (targetType?: string) => getData<PageResult<Record<string, unknown>>>('/admin/views', { targetType }),
  saveView: (data: Record<string, unknown>) => postData<Record<string, unknown>>('/admin/views', data),
  exports: () => getData<PageResult<ExportTask>>('/admin/exports'),
  createExport: (data: Record<string, unknown>) => postData<ExportTask>('/admin/exports', data),
  importTemplate: (type: string) => getData<Record<string, unknown>>(`/admin/imports/templates/${type}`),
  imports: (importType?: string) => getData<PageResult<ImportTask>>('/admin/imports', { importType }),
  importRows: (data: Record<string, unknown>) => postData<ImportTask>('/admin/imports', data),
  rules: (ruleCode?: string) => getData<PageResult<RuleParam>>('/admin/rules', { ruleCode }),
  saveRule: (data: Record<string, unknown>) => postData<RuleParam>('/admin/rules', data),
  publishRule: (id: number) => postData<RuleParam>(`/admin/rules/${id}/publish`),
  auditLogs: (businessType?: string) => getData<PageResult<AuditLog>>('/admin/audit-logs', { businessType }),
  publicConfirmation: (token: string) => getData<Sample>(`/public/confirm/${token}`),
  submitPublicConfirmation: (token: string, data: Record<string, unknown>) =>
    postData<Sample>(`/public/confirm/${token}/decision`, data),
  jobs: () => getData<PageResult<Record<string, unknown>>>('/admin/monitor/jobs'),
  runJob: (id: number) => postData<Record<string, unknown>>(`/admin/monitor/jobs/${id}/run`),
  systemUsers: () => getData<Array<Record<string, unknown>>>('/admin/system/users'),
  createSystemUser: (data: Record<string, unknown>) => postData<Record<string, unknown>>('/admin/system/users', data),
  systemRoles: () => getData<Array<Record<string, unknown>>>('/admin/system/roles'),
  createSystemRole: (data: Record<string, unknown>) => postData<Record<string, unknown>>('/admin/system/roles', data),
  rolePermissions: (roleId: number) => getData<any>(`/admin/system/roles/${roleId}/permissions`),
  replaceRolePermissions: (roleId: number, permissionCodes: string[]) => putData<any>(`/admin/system/roles/${roleId}/permissions`, { permissionCodes }),
  replaceSystemUserRoles: (userId: number, roleCodes: string[]) => putData<void>(`/admin/system/users/${userId}/roles`, { roleCodes }),
  departments: () => getData<Array<Record<string, unknown>>>('/admin/system/departments'),
  createDepartment: (data: Record<string, unknown>) => postData<Record<string, unknown>>('/admin/system/departments', data),
  systemMenus: () => getData<Array<Record<string, unknown>>>('/admin/system/menus'),
  createSystemMenu: (data: Record<string, unknown>) => postData<Record<string, unknown>>('/admin/system/menus', data),
  dictionaries: (type?: string) => getData<Array<Record<string, unknown>>>('/admin/system/dicts', { type }),
  saveDictionary: (data: Record<string, unknown>) => postData<Record<string, unknown>>('/admin/system/dicts', data),
  generatorTables: () => getData<PageResult<Record<string, unknown>>>('/admin/tool/gen/tables'),
  generatorPreview: (id: number) => getData<Record<string, string>>(`/admin/tool/gen/${id}/preview`)
}
